// Code generated by "stringer -type=Status,Reason -output verify_string.go verify.go"; DO NOT EDIT.

package skate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusExact-1]
	_ = x[StatusStrong-2]
	_ = x[StatusWeak-3]
	_ = x[StatusDifferent-4]
	_ = x[StatusAmbiguous-5]
}

const _Status_name = "StatusUnknownStatusExactStatusStrongStatusWeakStatusDifferentStatusAmbiguous"

var _Status_index = [...]uint8{0, 13, 24, 36, 46, 61, 76}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReasonUnknown-6]
	_ = x[ReasonAppendix-7]
	_ = x[ReasonArxivVersion-8]
	_ = x[ReasonBlacklisted-9]
	_ = x[ReasonBlacklistedFragment-10]
	_ = x[ReasonBookChapter-11]
	_ = x[ReasonChemFormula-12]
	_ = x[ReasonComponent-13]
	_ = x[ReasonContainer-14]
	_ = x[ReasonContainerNameBlacklist-15]
	_ = x[ReasonContribIntersectionEmpty-16]
	_ = x[ReasonCustomBSISubdoc-17]
	_ = x[ReasonCustomBSIUndated-18]
	_ = x[ReasonCustomIEEEArxiv-19]
	_ = x[ReasonCustomIOPMAPattern-20]
	_ = x[ReasonCustomPrefix1014288-21]
	_ = x[ReasonCustomPrefix105860ChoiceReview-22]
	_ = x[ReasonCustomPrefix107916-23]
	_ = x[ReasonCustomVHS-24]
	_ = x[ReasonDataciteRelatedID-25]
	_ = x[ReasonDataciteVersion-26]
	_ = x[ReasonDatasetDOI-27]
	_ = x[ReasonDOI-28]
	_ = x[ReasonFigshareVersion-29]
	_ = x[ReasonJaccardAuthors-30]
	_ = x[ReasonJstorID-31]
	_ = x[ReasonMaxClusterSizeExceeded-32]
	_ = x[ReasonNumDiff-33]
	_ = x[ReasonPageCount-34]
	_ = x[ReasonPMIDDOIPair-35]
	_ = x[ReasonPreprintPublished-36]
	_ = x[ReasonPublisherBlacklist-37]
	_ = x[ReasonReleaseType-38]
	_ = x[ReasonSharedDOIPrefix-39]
	_ = x[ReasonShortTitle-40]
	_ = x[ReasonSingularCluster-41]
	_ = x[ReasonSlugTitleAuthorMatch-42]
	_ = x[ReasonSubtitle-43]
	_ = x[ReasonTitleArtifact-44]
	_ = x[ReasonTitleAuthorMatch-45]
	_ = x[ReasonTitleFilename-46]
	_ = x[ReasonTokenizedAuthors-47]
	_ = x[ReasonVersionedDOI-48]
	_ = x[ReasonWorkID-49]
	_ = x[ReasonYear-50]
}

const _Reason_name = "ReasonUnknownReasonAppendixReasonArxivVersionReasonBlacklistedReasonBlacklistedFragmentReasonBookChapterReasonChemFormulaReasonComponentReasonContainerReasonContainerNameBlacklistReasonContribIntersectionEmptyReasonCustomBSISubdocReasonCustomBSIUndatedReasonCustomIEEEArxivReasonCustomIOPMAPatternReasonCustomPrefix1014288ReasonCustomPrefix105860ChoiceReviewReasonCustomPrefix107916ReasonCustomVHSReasonDataciteRelatedIDReasonDataciteVersionReasonDatasetDOIReasonDOIReasonFigshareVersionReasonJaccardAuthorsReasonJstorIDReasonMaxClusterSizeExceededReasonNumDiffReasonPageCountReasonPMIDDOIPairReasonPreprintPublishedReasonPublisherBlacklistReasonReleaseTypeReasonSharedDOIPrefixReasonShortTitleReasonSingularClusterReasonSlugTitleAuthorMatchReasonSubtitleReasonTitleArtifactReasonTitleAuthorMatchReasonTitleFilenameReasonTokenizedAuthorsReasonVersionedDOIReasonWorkIDReasonYear"

var _Reason_index = [...]uint16{0, 13, 27, 45, 62, 87, 104, 121, 136, 151, 179, 209, 230, 252, 273, 297, 322, 358, 382, 397, 420, 441, 457, 466, 487, 507, 520, 548, 561, 576, 593, 616, 640, 657, 678, 694, 715, 741, 755, 774, 796, 815, 837, 855, 867, 877}

func (i Reason) String() string {
	i -= 6
	if i < 0 || i >= Reason(len(_Reason_index)-1) {
		return "Reason(" + strconv.FormatInt(int64(i+6), 10) + ")"
	}
	return _Reason_name[_Reason_index[i]:_Reason_index[i+1]]
}
